#!/bin/bash

#higher number --> lower frequency
c_minus_one_raw=F260

tones=`bc -l <<EOF | sed 's/\..*//g' | sed -r 's/^(.*)$/0x\1,/g'
obase=16
ibase=16
scale=4A
$c_minus_one_raw
e(l(1/2)*1/C)*$c_minus_one_raw
e(l(1/2)*2/C)*$c_minus_one_raw
e(l(1/2)*3/C)*$c_minus_one_raw
e(l(1/2)*4/C)*$c_minus_one_raw
e(l(1/2)*5/C)*$c_minus_one_raw
e(l(1/2)*6/C)*$c_minus_one_raw
e(l(1/2)*7/C)*$c_minus_one_raw
e(l(1/2)*8/C)*$c_minus_one_raw
e(l(1/2)*9/C)*$c_minus_one_raw
e(l(1/2)*A/C)*$c_minus_one_raw
e(l(1/2)*B/C)*$c_minus_one_raw
e(l(1/2)*C/C)*$c_minus_one_raw
e(l(1/2)*D/C)*$c_minus_one_raw
e(l(1/2)*E/C)*$c_minus_one_raw
e(l(1/2)*F/C)*$c_minus_one_raw
EOF`

echo "//Generated by tune.sh" > tuning.h
echo $tones | sed -r 's/^(.*),$/const unsigned int tuning[0x10] = {\1};/' >> tuning.h