#ifndef MOTORPROTO_H
#define MOTORPROTO_H

/**
 *
 * Protocol for handling motor driver...
 *
*/

#define MOTORPROTO_HEAD     5
#define MOTORPROTO_DATA     0
#define MOTORPROTO_HEAD_GET 0b11100000
#define MOTORPROTO_DATA_GET 0b00011111

#define MOTORPROTO_INSTR_READ         (0b100 << MOTORPROTO_HEAD)
#define MOTORPROTO_INSTR_RESET        (0b010 << MOTORPROTO_HEAD)
#define MOTORPROTO_INSTR_SET_FORWARD  (0b101 << MOTORPROTO_HEAD)
#define MOTORPROTO_INSTR_SET_BACKWARD (0b110 << MOTORPROTO_HEAD)

#endif
